data:
  input_file: "./data/cleaned_station_data.csv"
  preprocessed_file: "./data/feature_engineered_data.csv"
model:
  sequence_length: 24
  hidden_size: 128
  num_layers: 3
  dropout: 0.3
  learning_rate: 1e-3
  epochs: 50
  batch_size: 32
  patience: 5
  step_size: 10
  gamma: 0.5
  device: "cuda"   # 如无GPU改为"cpu"
